// Generated by https://quicktype.io

export interface IssuesResponse {
    content:          Issue[];
    pageable:         Pageable;
    last:             boolean;
    totalElements:    number;
    totalPages:       number;
    first:            boolean;
    size:             number;
    number:           number;
    sort:             Sort;
    numberOfElements: number;
    empty:            boolean;
}

export interface Issue {
    id:               number;
    fechaProgramada:  string;   
    fechaRealizacion: string | null;
    anotaciones:      string;
    estacion:         Estacion;
    trabajador:       Trabajador;
    estado:           string;
}

export interface Estacion {
    id:          string;
    number:      number;
    name:        string;
    coordinates: string;
    capacity:    number;
    bikes:       number;
}

export interface Trabajador {
    id:     string;
    email:  string;
    nombre: string;
}


export interface Estacion {
    id:          string;
    number:      number;
    name:        string;
    coordinates: string;
    capacity:    number;
    bikes:       number;
}

export interface Trabajador {
    id:     string;
    email:  string;
    nombre: string;
}

export interface Pageable {
    pageNumber: number;
    pageSize:   number;
    sort:       Sort;
    offset:     number;
    paged:      boolean;
    unpaged:    boolean;
}

export interface Sort {
    empty:    boolean;
    unsorted: boolean;
    sorted:   boolean;
}