// Generated by https://quicktype.io

export interface NewIssue {
    fechaProgramada: string | null;
    anotaciones:     string;
    estacion:        Estacion;
    trabajador:      Trabajador;
    estado:          string;
}

export interface Estacion {
    id:          string;
    number:      number;
    name:        string;
    coordinates: string;
    capacity:    number;
    bikes:       number;
}

export interface Trabajador {
    id:     string;
    email:  string;
    nombre: string;
}
