// Generated by https://quicktype.io

export interface BikeUser {
    id:         string;
    createdAt:  string;
    email:      string;
    nombre:     string;
    username:   string;
    numTarjeta: string | null;
    pin:        string | null;
    saldo:      number;
}

export interface UserCardData{
    numTarjeta: string;
    pin:        string;
    pinCorfirmation: string;
}
