// Generated by https://quicktype.io
// Generated by https://quicktype.io

export interface UsoResponse {
    id: number;
    fechaInicio: string;
    fechaFin: null;
    coste: number;
    bicicleta: string;
    estacionFin: string;
    usuario: string;
}

export interface UsoBegin {
    id: number;
    fechaInicio: string;
    bicicleta: string;
    usuario: string;
    estacionInicio: string;
}
